// <auto-generated />
using Challenge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Challenge.Api.Data.Migrations
{
    [DbContext(typeof(CategoryContext))]
    partial class CategoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Challenge.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Fiction"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Non-Fiction"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Science Fiction"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
